### ISSUE TITLE
pull requests are not being associated with coveralls builds.

### ISSUE THREAD

**Issue by azjezz** [cedx/coveralls.php#11]
PR by maintainer:
 https://github.com/azjezz/psl/pull/77
 https://coveralls.io/builds/33917335 ( pr )
 https://coveralls.io/builds/33917345 ( branch ) 

PR by contributor:
  https://github.com/azjezz/psl/pull/78
  https://coveralls.io/builds/33917877 ( pr )

while coveralls check works, it only works when a maintainer creates a PR, but not any contributor, and no comments are left about the changes in code coverage.

am I doing something wrong here? 🤔

**Comment by cedx** [comment]
@SamMousa I don't plan to maintain this project anymore. I suggest you to use [php-coveralls](https://packagist.org/packages/php-coveralls/php-coveralls) instead.
