### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by SamMousa** [cedx/coveralls.php#12]
I'm not seeing anything on the coveralls.io side, but the tool is finishing with error code 0.
Enabling debug output via `-vvv` doesn't provide any relevant debug output.

I'd expect to see all API requests logged if we use the maximum verbosity option.

**Comment by cedx** [comment]
@SamMousa I don't plan to maintain this project anymore. I suggest you to use [php-coveralls](https://packagist.org/packages/php-coveralls/php-coveralls) instead.
